version: '3'
services:
  phpstorm:
    build:
      context: ./phpstorm
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/var/www
      - ./phpstorm/config:/home/www-data/.PhpStorm2018.3/config
      - ./phpstorm/system:/home/www-data/.PhpStorm2018.3/system
    links:
      - php-fpm:php
    networks:
      - backend

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www
    environment:
      - XDEBUG_CONFIG="remote_autostart=1 remote_host=phpstorm remote_port=9001 remote_enable=1 idekey=PHPSTORM"
    networks:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm:php
    networks:
      - backend
    ports:
      - 8080:80

  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  backend:
    driver: "bridge"
