version: '3'
services:
  php-fpm:
    build:
      context: ./php-fpm
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ./src:/app
    network_mode: host
    ports:
      - 9002:9000

  nginx:
    image: nginx
    volumes:
      - ./src:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm:php
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PHP_FPM=localhost:9000
